### ISSUE TITLE
Add "set gate height" action to Control Structures

### ISSUE THREAD

**Issue by GolnesaK** [nens/threedi-schema#38]
Add "set_gate_height" to control structures. Gate height in m MSL

**Comment by leendertvanwolfswinkel** [comment]
How would this work if users try to do this for open cross-sections?

**Comment by jpprins1** [comment]
Does the calcore already support this feature? And if so, how does the function call looks like?

**Comment by GolnesaK** [comment]
> Does the calcore already support this feature? And if so, how does the function call looks like?

@jpprins1
It is already added to the calcore (not in master yet). You can check it out in the branch "golnesa-controlStructure-rectangle" in structure_actions.f90.  It's called "set_gate_height".

**Comment by leendertvanwolfswinkel** [comment]
I think the implementation can be analogous to set_discharge_coefficients. Valid combinations with `set_gate_height` would be `v2_orifice`, `v2_weir`, `v2_pipe`, `v2_channel`, and `v2_culvert`. Pipe, channel (and also culvert I suppose?) are "for internal use only" and use a `flowline id` (btw @jpprins1 can you please use flowline id instead of grid_id in the api reference?) instead of a `structure_id`

**Comment by GolnesaK** [comment]
@jpprins1 @leendertvanwolfswinkel 
A correction on the name of this new action; it is "set_gate_level", instead of "set_gate_height" (since we established the gate definition to be absolute)
