### ISSUE TITLE
Control measure map geometry is reversed

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-schema#96]
The structure control migration should generate a line from control_measure_location.geom to table_control.geom or from control_measure_location.geom to memory_control.geom, but the geometry that is created is reversed.

And please draw the line to the start connection node of the v2_pumpstation, not to "in between start and end node"

**Comment by margrietpalm** [comment]
@leendertvanwolfswinkel 

The Excel states that the `table_control.geom` or `memory_control.geom` should be:

> Use the center point (ST_InterpolatePoint(the_geom, 0.5)) of the object indicated by the value in target_type with the ID target_id

Because `control_measure_map.geom` is the line from `control_measure_location.geom` to `*_control.geom`. So given the definition above, this is why for `v2_pumpstation` one of the line ends is "in between start and end node". The easy fix would be to change the definition for `v2_pumpstation.geom` to the start node of `v2_pumpstation`. Is this ok?

**Comment by margrietpalm** [comment]
Ensure that `control_measure_map.geom` is a valid geom (https://github.com/nens/threedi-schema/issues/102)

**Comment by leendertvanwolfswinkel** [comment]
Tested and it works as expected
